language: c
before_install:
 - sudo apt-get install libcap-dev libglib2.0-dev libmhash-dev libkqueue.* libcgroup-dev
 - sudo pip install cpp-coveralls --use-mirrors
script:
 - ./.travis.sh
after_success:
 - coveralls -x c --exclude examples --exclude debian --exclude gentoo --exclude freebsd --exclude m4 --exclude autom4te.cache --exclude man --exclude conf*.dir --exclude cluster.c
